### ISSUE TITLE
Test Fake TLS proxy

### ISSUE THREAD

**Issue by amyrprv** [MTProto/MTProtoProxy#4]
Hi,
I want to check if a running proxy is available and it's not banned??
Is it possible to test fake-TLS proxy in Nodejs??

**Comment by MTProto** [comment]
> Hi,
> I want to check if a running proxy is available and it's not banned??
> Is it possible to test fake-TLS proxy in Nodejs??

Of course, this is possible; but this repository is not intended for the checking of proxy servers. Unfortunately I am not interested in sharing the code here, because it may be abused by auto-filtering systems especially in Iran. But if you want to develop your own code, you can refer to telegram core documentation, 'PING' command.
If you are using this repository code, you can simply load http report. It may help.

**Comment by amirh3n** [comment]
> > Hi,
> > I want to check if a running proxy is available and it's not banned??
> > Is it possible to test fake-TLS proxy in Nodejs??
> 
> Of course, this is possible; but this repository is non intended for the checking of proxy servers. Unfortunately I am not interested in sharing the code here, because it may be abused by auto-filtering systems especially in Iran. But if you want to develop your own code, you can refer to telegram core documentation, 'PING' command.
> If you are using this repository code, you can simply load http report. It may help.

Can we discuss on telegram, @NimaPaymard
